### PR TITLE
2024 Updates

### PR DESCRIPTION
**Pull request by JasonBrave**
Prevent output period character when received duplicate CAN messages
Improve code quality

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_usb/17)

### CODE REVIEW

**Review by StarlightDescender — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_usb/17)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH, @DomenicHampson, @Joe-Joe-Joe-Joe, and @Lucifersan)

**Comment by BluCodeGH** [comment]
Does .clang-format need to be in the root of the repo? Would be best if it could live in canlib so there is one source of truth to update.

**Review by Lucifersan — APPROVED** [review]
optimization so good

**Comment by JasonBrave** [comment]
1. Having clang-format file at root repository make it easier for people with editor built-in clang-format to format code directly in editor.
2. The issue with symbolic link is it will cause issue on windows.
3. USB Debug FW does not use rocketlib

**Review by BluCodeGH — APPROVED** [review]

**Pull request merged**
